module.exports = {
  MESSAGES: {
    INVALID_CREDENTIALS: "Invalid email or password.",
    INVALID_PASSWORD: "Invalid password.",
    TOKEN_REQUIRED: "Authentication token is required",
    INVALID_TOKEN: "Invalid authentication token",
    INTERNAL_SERVER_ERROR: "Internal server error",
    UNAUTHORIZED: "Unauthorized: You do not have permission to access this resource.",
    NOT_FOUND: "Resource not found",
    SUCCESS: "Operation completed successfully",
  },
  MONTH_LIST: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  ROLES: {
    ADMIN: "admin",
    USER: "user",
  },
};
